#!/bin/bash

# Update the package list
sudo apt update -y

# Install Git and Python3-pip
sudo apt install git -y
sudo apt install python3-pip -y

# Clone the repository (adjust the repository URL if necessary)
cd /home/ubuntu/
git clone https://github.com/vasanthi111/USA-Housing.git

# Navigate to the cloned repository
cd /home/ubuntu/USA-Housing

# Install the required Python packages
pip3 install -r requirements.txt

# Run the Python application in the background using screen
screen -m -d python3 ./app.py
